GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test title",
    "author": "Test author",
    "url": "Test url",
    "likes": 3
}
###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "nate",
    "name": "Nate Se",
    "password": "DomeZa"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "nate",
    "password": "DomeZa"
}

###

DELETE http://localhost:3003/api/blogs/69a79914e11480f890e0003c
