GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

###
GET http://localhost:3001/api/notes/123

###
GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "nate",
    "name": "Nate Se",
    "password": "DomeZa"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Test Nate id of the note creator",
    "important": true,
    "userId": "69a61dbe60a4395dcc25d52d"
}